import type { PanelType, PanelConfig, PanelLayout } from "./dashboard-types";

export interface DashboardTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  panels: {
    title: string;
    panel_type: PanelType;
    config: PanelConfig;
    layout: PanelLayout;
  }[];
}

export const DASHBOARD_TEMPLATES: DashboardTemplate[] = [
  {
    id: "relay-overview",
    name: "Relay Overview",
    description: "Connect latency, event latency, and uptime for your relays",
    icon: "⚡",
    panels: [
      {
        title: "Connect Latency",
        panel_type: "line",
        config: { metric_key: "relay_latency_connect_ms", data_source: "relay" as const, unit: "ms" },
        layout: { x: 0, y: 0, w: 6, h: 4 },
      },
      {
        title: "Event Latency",
        panel_type: "line",
        config: { metric_key: "relay_latency_first_event_ms", data_source: "relay" as const, unit: "ms" },
        layout: { x: 6, y: 0, w: 6, h: 4 },
      },
      {
        title: "Uptime",
        panel_type: "gauge",
        config: { metric_key: "relay_up", data_source: "relay" as const, stat_field: "avg" as const, gauge_max: 1 },
        layout: { x: 0, y: 4, w: 4, h: 3 },
      },
      {
        title: "Avg Connect Time",
        panel_type: "stat",
        config: { metric_key: "relay_latency_connect_ms", data_source: "relay" as const, stat_field: "avg" as const, unit: "ms" },
        layout: { x: 4, y: 4, w: 4, h: 2 },
      },
      {
        title: "P95 Connect Time",
        panel_type: "stat",
        config: { metric_key: "relay_latency_connect_ms", data_source: "relay" as const, stat_field: "p95" as const, unit: "ms" },
        layout: { x: 8, y: 4, w: 4, h: 2 },
      },
    ],
  },
  {
    id: "network-health",
    name: "Network Health",
    description: "Network-wide throughput, active relays, and latency trends",
    icon: "🌐",
    panels: [
      {
        title: "Event Throughput",
        panel_type: "area",
        config: { metric_key: "network_event_throughput", data_source: "global" as const, unit: "events/s" },
        layout: { x: 0, y: 0, w: 8, h: 4 },
      },
      {
        title: "Active Relays",
        panel_type: "stat",
        config: { metric_key: "network_relay_count", data_source: "global" as const, stat_field: "latest" as const, unit: "relays" },
        layout: { x: 8, y: 0, w: 4, h: 2 },
      },
      {
        title: "Network Avg Latency",
        panel_type: "stat",
        config: { metric_key: "network_avg_latency", data_source: "global" as const, stat_field: "avg" as const, unit: "ms" },
        layout: { x: 8, y: 2, w: 4, h: 2 },
      },
      {
        title: "Network Latency Trend",
        panel_type: "line",
        config: { metric_key: "network_avg_latency", data_source: "global" as const, unit: "ms" },
        layout: { x: 0, y: 4, w: 12, h: 4 },
      },
    ],
  },
  {
    id: "zap-economy",
    name: "Zap Economy",
    description: "Lightning zap volumes, counts, and averages over time",
    icon: "💰",
    panels: [
      {
        title: "Zap Volume",
        panel_type: "area",
        config: { metric_key: "zap_volume_sats", data_source: "global" as const, unit: "sats" },
        layout: { x: 0, y: 0, w: 8, h: 4 },
      },
      {
        title: "Total Zaps",
        panel_type: "stat",
        config: { metric_key: "zap_count", data_source: "global" as const, stat_field: "latest" as const, unit: "zaps" },
        layout: { x: 8, y: 0, w: 4, h: 2 },
      },
      {
        title: "Avg Zap Size",
        panel_type: "stat",
        config: { metric_key: "zap_avg_size", data_source: "global" as const, stat_field: "avg" as const, unit: "sats" },
        layout: { x: 8, y: 2, w: 4, h: 2 },
      },
      {
        title: "Zap Count Over Time",
        panel_type: "line",
        config: { metric_key: "zap_count", data_source: "global" as const, unit: "zaps" },
        layout: { x: 0, y: 4, w: 6, h: 4 },
      },
      {
        title: "Median Zap Size",
        panel_type: "line",
        config: { metric_key: "zap_median_size", data_source: "global" as const, unit: "sats" },
        layout: { x: 6, y: 4, w: 6, h: 4 },
      },
    ],
  },
  {
    id: "protocol-stats",
    name: "Protocol Analytics",
    description: "Event kinds, propagation times, and NIP compatibility",
    icon: "📡",
    panels: [
      {
        title: "Text Notes (kind 1)",
        panel_type: "line",
        config: { metric_key: "event_kind_1_count", data_source: "global" as const, unit: "events" },
        layout: { x: 0, y: 0, w: 6, h: 4 },
      },
      {
        title: "Reactions (kind 7)",
        panel_type: "line",
        config: { metric_key: "event_kind_7_count", data_source: "global" as const, unit: "events" },
        layout: { x: 6, y: 0, w: 6, h: 4 },
      },
      {
        title: "Event Propagation",
        panel_type: "area",
        config: { metric_key: "event_propagation_ms", data_source: "global" as const, unit: "ms" },
        layout: { x: 0, y: 4, w: 8, h: 4 },
      },
      {
        title: "NIP Support Score",
        panel_type: "gauge",
        config: { metric_key: "nip_support_score", data_source: "global" as const, stat_field: "avg" as const, gauge_max: 100 },
        layout: { x: 8, y: 4, w: 4, h: 3 },
      },
    ],
  },
  {
    id: "vercel-site",
    name: "Vercel Site",
    description: "Deploy counts, build durations, and error rates for your Vercel projects",
    icon: "▲",
    panels: [
      { title: "Deploys", panel_type: "area", config: { metric_key: "deploy.count", data_source: "custom" as const, unit: "deploys" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "Total Deploys", panel_type: "stat", config: { metric_key: "deploy.count", data_source: "custom" as const, stat_field: "sum" as const, unit: "deploys" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Avg Build Time", panel_type: "stat", config: { metric_key: "build.duration_ms", data_source: "custom" as const, stat_field: "avg" as const, unit: "ms" }, layout: { x: 8, y: 2, w: 4, h: 2 } },
      { title: "Build Duration Trend", panel_type: "line", config: { metric_key: "build.duration_ms", data_source: "custom" as const, unit: "ms" }, layout: { x: 0, y: 4, w: 6, h: 4 } },
      { title: "Error Rate", panel_type: "line", config: { metric_key: "error.count", data_source: "custom" as const, unit: "errors" }, layout: { x: 6, y: 4, w: 6, h: 4 } },
    ],
  },
  {
    id: "github-project",
    name: "GitHub Project",
    description: "Stars, forks, open issues, and PR velocity for your repositories",
    icon: "🐙",
    panels: [
      { title: "Stars", panel_type: "area", config: { metric_key: "github.stars", data_source: "custom" as const, unit: "stars" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "Total Stars", panel_type: "stat", config: { metric_key: "github.stars", data_source: "custom" as const, stat_field: "latest" as const, unit: "stars" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Open Issues", panel_type: "stat", config: { metric_key: "github.open_issues", data_source: "custom" as const, stat_field: "latest" as const, unit: "issues" }, layout: { x: 8, y: 2, w: 4, h: 2 } },
      { title: "Forks", panel_type: "line", config: { metric_key: "github.forks", data_source: "custom" as const, unit: "forks" }, layout: { x: 0, y: 4, w: 6, h: 4 } },
      { title: "PRs Merged", panel_type: "area", config: { metric_key: "github.prs_merged", data_source: "custom" as const, unit: "PRs" }, layout: { x: 6, y: 4, w: 6, h: 4 } },
    ],
  },
  {
    id: "uptime-overview",
    name: "Uptime Overview",
    description: "Uptime percentage, latency trends, and incident counts",
    icon: "🟢",
    panels: [
      { title: "Uptime %", panel_type: "gauge", config: { metric_key: "uptime.pct", data_source: "custom" as const, stat_field: "avg" as const, gauge_max: 100 }, layout: { x: 0, y: 0, w: 4, h: 3 } },
      { title: "Avg Latency", panel_type: "stat", config: { metric_key: "uptime.latency_ms", data_source: "custom" as const, stat_field: "avg" as const, unit: "ms" }, layout: { x: 4, y: 0, w: 4, h: 2 } },
      { title: "Incidents", panel_type: "stat", config: { metric_key: "uptime.incidents", data_source: "custom" as const, stat_field: "sum" as const, unit: "incidents" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Latency Over Time", panel_type: "line", config: { metric_key: "uptime.latency_ms", data_source: "custom" as const, unit: "ms" }, layout: { x: 0, y: 3, w: 12, h: 4 } },
    ],
  },
  {
    id: "nostr-relays",
    name: "Nostr Relays",
    description: "DB size and pubkey counts for your self-hosted Haven or Khatru relays",
    icon: "⚡",
    panels: [
      { title: "Relay 1 DB Size", panel_type: "area", config: { metric_key: "relay.relay1.db_size_mb", data_source: "custom" as const, unit: "MB" }, layout: { x: 0, y: 0, w: 6, h: 4 } },
      { title: "Relay 2 DB Size", panel_type: "area", config: { metric_key: "relay.relay2.db_size_mb", data_source: "custom" as const, unit: "MB" }, layout: { x: 6, y: 0, w: 6, h: 4 } },
      { title: "Relay 1 DB", panel_type: "stat", config: { metric_key: "relay.relay1.db_size_mb", data_source: "custom" as const, stat_field: "latest" as const, unit: "MB" }, layout: { x: 0, y: 4, w: 3, h: 2 } },
      { title: "Relay 2 DB", panel_type: "stat", config: { metric_key: "relay.relay2.db_size_mb", data_source: "custom" as const, stat_field: "latest" as const, unit: "MB" }, layout: { x: 3, y: 4, w: 3, h: 2 } },
      { title: "Relay 1 Pubkeys", panel_type: "stat", config: { metric_key: "relay.relay1.pubkeys", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 6, y: 4, w: 3, h: 2 } },
      { title: "Relay 3 DB", panel_type: "stat", config: { metric_key: "relay.relay3.db_size_mb", data_source: "custom" as const, stat_field: "latest" as const, unit: "MB" }, layout: { x: 9, y: 4, w: 3, h: 2 } },
    ],
  },
  {
    id: "github-projects",
    name: "GitHub Projects",
    description: "Stars, issues, and forks across your active repos",
    icon: "🚀",
    panels: [
      { title: "Repo 1 Stars", panel_type: "area", config: { metric_key: "github.user.repo1.stars", data_source: "custom" as const, unit: "⭐" }, layout: { x: 0, y: 0, w: 4, h: 4 } },
      { title: "Repo 2 Stars", panel_type: "area", config: { metric_key: "github.user.repo2.stars", data_source: "custom" as const, unit: "⭐" }, layout: { x: 4, y: 0, w: 4, h: 4 } },
      { title: "Repo 3 Stars", panel_type: "area", config: { metric_key: "github.user.repo3.stars", data_source: "custom" as const, unit: "⭐" }, layout: { x: 8, y: 0, w: 4, h: 4 } },
      { title: "Repo 1 Issues", panel_type: "stat", config: { metric_key: "github.user.repo1.issues", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 0, y: 4, w: 4, h: 2 } },
      { title: "Repo 2 Issues", panel_type: "stat", config: { metric_key: "github.user.repo2.issues", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 4, y: 4, w: 4, h: 2 } },
      { title: "Repo 3 Issues", panel_type: "stat", config: { metric_key: "github.user.repo3.issues", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 8, y: 4, w: 4, h: 2 } },
    ],
  },
  {
    id: "mac-mini-health",
    name: "Mac Mini Health",
    description: "CPU, RAM, disk usage and Jellyfin stats for your home server",
    icon: "🖥️",
    panels: [
      { title: "CPU Usage", panel_type: "area", config: { metric_key: "system.cpu_pct", data_source: "custom" as const, unit: "%" }, layout: { x: 0, y: 0, w: 6, h: 4 } },
      { title: "RAM Usage", panel_type: "area", config: { metric_key: "system.ram_pct", data_source: "custom" as const, unit: "%" }, layout: { x: 6, y: 0, w: 6, h: 4 } },
      { title: "CPU %", panel_type: "stat", config: { metric_key: "system.cpu_pct", data_source: "custom" as const, stat_field: "latest" as const, unit: "%" }, layout: { x: 0, y: 4, w: 3, h: 2 } },
      { title: "RAM %", panel_type: "stat", config: { metric_key: "system.ram_pct", data_source: "custom" as const, stat_field: "latest" as const, unit: "%" }, layout: { x: 3, y: 4, w: 3, h: 2 } },
      { title: "RAM Used", panel_type: "stat", config: { metric_key: "system.ram_used_mb", data_source: "custom" as const, stat_field: "latest" as const, unit: "MB" }, layout: { x: 6, y: 4, w: 3, h: 2 } },
      { title: "External Disk", panel_type: "gauge", config: { metric_key: "system.disk_external_pct", data_source: "custom" as const, stat_field: "latest" as const, gauge_max: 100, unit: "%" }, layout: { x: 9, y: 4, w: 3, h: 3 } },
      { title: "Boot Disk", panel_type: "gauge", config: { metric_key: "system.disk_boot_pct", data_source: "custom" as const, stat_field: "latest" as const, gauge_max: 100, unit: "%" }, layout: { x: 0, y: 6, w: 3, h: 3 } },
      { title: "Disk Free (GB)", panel_type: "stat", config: { metric_key: "system.disk_external_free_gb", data_source: "custom" as const, stat_field: "latest" as const, unit: "GB" }, layout: { x: 3, y: 6, w: 3, h: 2 } },
      { title: "Jellyfin Streams", panel_type: "area", config: { metric_key: "jellyfin.active_streams", data_source: "custom" as const, unit: "streams" }, layout: { x: 0, y: 9, w: 6, h: 4 } },
      { title: "Active Streams", panel_type: "stat", config: { metric_key: "jellyfin.active_streams", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 6, y: 9, w: 3, h: 2 } },
      { title: "Songs in Library", panel_type: "stat", config: { metric_key: "jellyfin.song_count", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 9, y: 9, w: 3, h: 2 } },
      { title: "Albums", panel_type: "stat", config: { metric_key: "jellyfin.album_count", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 6, y: 11, w: 3, h: 2 } },
      { title: "Connected Clients", panel_type: "stat", config: { metric_key: "jellyfin.connected_clients", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 9, y: 11, w: 3, h: 2 } },
    ],
  },
  {
    id: "plex-media-server",
    name: "Plex Media Server",
    description: "Active streams and library counts for your Plex server",
    icon: "🎬",
    panels: [
      { title: "Active Streams", panel_type: "area", config: { metric_key: "plex.active_streams", data_source: "custom" as const, unit: "streams" }, layout: { x: 0, y: 0, w: 12, h: 4 } },
      { title: "Streams Now", panel_type: "stat", config: { metric_key: "plex.active_streams", data_source: "custom" as const, stat_field: "latest" as const, unit: "" }, layout: { x: 0, y: 4, w: 3, h: 2 } },
      { title: "Movies", panel_type: "stat", config: { metric_key: "plex.library.movies.count", data_source: "custom" as const, stat_field: "latest" as const, unit: "titles" }, layout: { x: 3, y: 4, w: 3, h: 2 } },
      { title: "TV Shows", panel_type: "stat", config: { metric_key: "plex.library.tv_shows.count", data_source: "custom" as const, stat_field: "latest" as const, unit: "shows" }, layout: { x: 6, y: 4, w: 3, h: 2 } },
      { title: "Music", panel_type: "stat", config: { metric_key: "plex.library.music.count", data_source: "custom" as const, stat_field: "latest" as const, unit: "tracks" }, layout: { x: 9, y: 4, w: 3, h: 2 } },
      { title: "Audiobooks", panel_type: "stat", config: { metric_key: "plex.library.audiobooks.count", data_source: "custom" as const, stat_field: "latest" as const, unit: "titles" }, layout: { x: 0, y: 6, w: 3, h: 2 } },
      { title: "Movies Library Trend", panel_type: "area", config: { metric_key: "plex.library.movies.count", data_source: "custom" as const, unit: "titles" }, layout: { x: 0, y: 8, w: 6, h: 4 } },
      { title: "TV Shows Library Trend", panel_type: "area", config: { metric_key: "plex.library.tv_shows.count", data_source: "custom" as const, unit: "shows" }, layout: { x: 6, y: 8, w: 6, h: 4 } },
    ],
  },
  {
    id: "personal-overview",
    name: "Personal Overview",
    description: "BTC price, Nostr follower counts, and GitHub project stars — track your presence",
    icon: "🧑‍💻",
    panels: [
      { title: "BTC Price", panel_type: "area", config: { metric_key: "bitcoin.price_usd", data_source: "custom" as const, unit: "USD" }, layout: { x: 0, y: 0, w: 12, h: 4 } },
      { title: "BTC Price", panel_type: "stat", config: { metric_key: "bitcoin.price_usd", data_source: "custom" as const, stat_field: "latest" as const, unit: "$" }, layout: { x: 0, y: 4, w: 4, h: 2 } },
      { title: "Nostr Followers (Account 1)", panel_type: "stat", config: { metric_key: "nostr.account1.followers", data_source: "custom" as const, stat_field: "latest" as const, unit: "followers" }, layout: { x: 4, y: 4, w: 4, h: 2 } },
      { title: "Nostr Followers (Account 2)", panel_type: "stat", config: { metric_key: "nostr.account2.followers", data_source: "custom" as const, stat_field: "latest" as const, unit: "followers" }, layout: { x: 8, y: 4, w: 4, h: 2 } },
      { title: "Repo 1 Stars", panel_type: "stat", config: { metric_key: "github.user.repo1.stars", data_source: "custom" as const, stat_field: "latest" as const, unit: "⭐" }, layout: { x: 0, y: 6, w: 4, h: 2 } },
      { title: "Repo 2 Stars", panel_type: "stat", config: { metric_key: "github.user.repo2.stars", data_source: "custom" as const, stat_field: "latest" as const, unit: "⭐" }, layout: { x: 4, y: 6, w: 4, h: 2 } },
    ],
  },
  {
    id: "personal-stats",
    name: "Personal Stats",
    description: "Track anything about yourself — commits, workouts, sleep, habits",
    icon: "📊",
    panels: [
      { title: "Daily Commits", panel_type: "area", config: { metric_key: "dev.commits", data_source: "custom" as const, unit: "commits" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "Streak", panel_type: "stat", config: { metric_key: "dev.streak_days", data_source: "custom" as const, stat_field: "latest" as const, unit: "days" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Habit Score", panel_type: "gauge", config: { metric_key: "habit.score", data_source: "custom" as const, stat_field: "avg" as const, gauge_max: 100 }, layout: { x: 8, y: 2, w: 4, h: 3 } },
      { title: "Custom Metric 1", panel_type: "line", config: { metric_key: "custom.metric_1", data_source: "custom" as const, unit: "" }, layout: { x: 0, y: 4, w: 6, h: 4 } },
      { title: "Custom Metric 2", panel_type: "line", config: { metric_key: "custom.metric_2", data_source: "custom" as const, unit: "" }, layout: { x: 6, y: 4, w: 6, h: 4 } },
    ],
  },
  {
    id: "mempool-dashboard",
    name: "Mempool Dashboard",
    description: "Bitcoin fee rates, block height, hashrate, and mempool stats from mempool.space",
    icon: "⛓️",
    panels: [
      { title: "Fastest Fee", panel_type: "area", config: { metric_key: "mempool.fees.fastest", data_source: "custom" as const, unit: "sat/vB" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "Fastest Fee", panel_type: "stat", config: { metric_key: "mempool.fees.fastest", data_source: "custom" as const, stat_field: "latest" as const, unit: "sat/vB" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Economy Fee", panel_type: "stat", config: { metric_key: "mempool.fees.economy", data_source: "custom" as const, stat_field: "latest" as const, unit: "sat/vB" }, layout: { x: 8, y: 2, w: 4, h: 2 } },
      { title: "1-Hour Fee", panel_type: "line", config: { metric_key: "mempool.fees.hour", data_source: "custom" as const, unit: "sat/vB" }, layout: { x: 0, y: 4, w: 6, h: 4 } },
      { title: "Block Height", panel_type: "stat", config: { metric_key: "mempool.block_height", data_source: "custom" as const, stat_field: "latest" as const, unit: "blocks" }, layout: { x: 6, y: 4, w: 3, h: 2 } },
      { title: "Mempool TX Count", panel_type: "stat", config: { metric_key: "mempool.tx_count", data_source: "custom" as const, stat_field: "latest" as const, unit: "txs" }, layout: { x: 9, y: 4, w: 3, h: 2 } },
      { title: "Hashrate", panel_type: "area", config: { metric_key: "mempool.hashrate", data_source: "custom" as const, unit: "EH/s" }, layout: { x: 0, y: 8, w: 8, h: 4 } },
      { title: "Hashrate Now", panel_type: "stat", config: { metric_key: "mempool.hashrate", data_source: "custom" as const, stat_field: "latest" as const, unit: "EH/s" }, layout: { x: 8, y: 8, w: 4, h: 2 } },
    ],
  },
  {
    id: "network-speed",
    name: "Network Speed",
    description: "Download/upload trends, ping, and jitter from periodic speedtests",
    icon: "🚀",
    panels: [
      { title: "Download Speed", panel_type: "area", config: { metric_key: "speedtest.download_mbps", data_source: "custom" as const, unit: "Mbps" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "Download Now", panel_type: "stat", config: { metric_key: "speedtest.download_mbps", data_source: "custom" as const, stat_field: "latest" as const, unit: "Mbps" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Upload Now", panel_type: "stat", config: { metric_key: "speedtest.upload_mbps", data_source: "custom" as const, stat_field: "latest" as const, unit: "Mbps" }, layout: { x: 8, y: 2, w: 4, h: 2 } },
      { title: "Upload Speed", panel_type: "area", config: { metric_key: "speedtest.upload_mbps", data_source: "custom" as const, unit: "Mbps" }, layout: { x: 0, y: 4, w: 8, h: 4 } },
      { title: "Ping", panel_type: "stat", config: { metric_key: "speedtest.ping_ms", data_source: "custom" as const, stat_field: "latest" as const, unit: "ms" }, layout: { x: 8, y: 4, w: 2, h: 2 } },
      { title: "Jitter", panel_type: "stat", config: { metric_key: "speedtest.jitter_ms", data_source: "custom" as const, stat_field: "latest" as const, unit: "ms" }, layout: { x: 10, y: 4, w: 2, h: 2 } },
      { title: "Ping Trend", panel_type: "line", config: { metric_key: "speedtest.ping_ms", data_source: "custom" as const, unit: "ms" }, layout: { x: 0, y: 8, w: 12, h: 4 } },
    ],
  },
  {
    id: "music-listening",
    name: "Music Listening",
    description: "Total listens, daily activity, and weekly listening trends from ListenBrainz",
    icon: "🎧",
    panels: [
      { title: "Total Listens", panel_type: "stat", config: { metric_key: "listenbrainz.total_listens", data_source: "custom" as const, stat_field: "latest" as const, unit: "listens" }, layout: { x: 0, y: 0, w: 4, h: 2 } },
      { title: "Today", panel_type: "stat", config: { metric_key: "listenbrainz.listens_today", data_source: "custom" as const, stat_field: "latest" as const, unit: "listens" }, layout: { x: 4, y: 0, w: 4, h: 2 } },
      { title: "This Week", panel_type: "stat", config: { metric_key: "listenbrainz.listens_this_week", data_source: "custom" as const, stat_field: "latest" as const, unit: "listens" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Daily Listens", panel_type: "area", config: { metric_key: "listenbrainz.listens_today", data_source: "custom" as const, unit: "listens" }, layout: { x: 0, y: 2, w: 12, h: 4 } },
      { title: "Weekly Listens", panel_type: "line", config: { metric_key: "listenbrainz.listens_this_week", data_source: "custom" as const, unit: "listens" }, layout: { x: 0, y: 6, w: 12, h: 4 } },
    ],
  },
  {
    id: "market-overview",
    name: "Market Overview",
    description: "BTC dominance, total crypto market cap, M2 money supply, and Fed funds rate",
    icon: "📈",
    panels: [
      { title: "BTC Dominance", panel_type: "area", config: { metric_key: "coingecko.btc_dominance", data_source: "custom" as const, unit: "%" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "BTC Dom.", panel_type: "stat", config: { metric_key: "coingecko.btc_dominance", data_source: "custom" as const, stat_field: "latest" as const, unit: "%" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Total Market Cap", panel_type: "stat", config: { metric_key: "coingecko.total_market_cap_usd", data_source: "custom" as const, stat_field: "latest" as const, unit: "USD" }, layout: { x: 8, y: 2, w: 4, h: 2 } },
      { title: "Total Market Cap", panel_type: "area", config: { metric_key: "coingecko.total_market_cap_usd", data_source: "custom" as const, unit: "USD" }, layout: { x: 0, y: 4, w: 8, h: 4 } },
      { title: "24h Volume", panel_type: "stat", config: { metric_key: "coingecko.total_volume_24h", data_source: "custom" as const, stat_field: "latest" as const, unit: "USD" }, layout: { x: 8, y: 4, w: 4, h: 2 } },
      { title: "M2 Money Supply", panel_type: "line", config: { metric_key: "fred.m2_money_supply", data_source: "custom" as const, unit: "$B" }, layout: { x: 0, y: 8, w: 6, h: 4 } },
      { title: "Fed Funds Rate", panel_type: "line", config: { metric_key: "fred.fed_funds_rate", data_source: "custom" as const, unit: "%" }, layout: { x: 6, y: 8, w: 3, h: 4 } },
      { title: "CPI", panel_type: "line", config: { metric_key: "fred.cpi", data_source: "custom" as const, unit: "" }, layout: { x: 9, y: 8, w: 3, h: 4 } },
    ],
  },
  {
    id: "weather-station",
    name: "Weather Station",
    description: "Temperature, rain, snow, wind, and UV index for your location",
    icon: "🌤️",
    panels: [
      { title: "Temperature", panel_type: "area", config: { metric_key: "weather.home.temperature", data_source: "custom" as const, unit: "°C" }, layout: { x: 0, y: 0, w: 8, h: 4 } },
      { title: "Temp Now", panel_type: "stat", config: { metric_key: "weather.home.temperature", data_source: "custom" as const, stat_field: "latest" as const, unit: "°C" }, layout: { x: 8, y: 0, w: 4, h: 2 } },
      { title: "Humidity", panel_type: "stat", config: { metric_key: "weather.home.humidity", data_source: "custom" as const, stat_field: "latest" as const, unit: "%" }, layout: { x: 8, y: 2, w: 4, h: 2 } },
      { title: "Wind Speed", panel_type: "line", config: { metric_key: "weather.home.wind_speed", data_source: "custom" as const, unit: "km/h" }, layout: { x: 0, y: 4, w: 6, h: 4 } },
      { title: "UV Index", panel_type: "gauge", config: { metric_key: "weather.home.uv_index", data_source: "custom" as const, stat_field: "latest" as const, gauge_max: 11 }, layout: { x: 6, y: 4, w: 3, h: 3 } },
      { title: "Rain", panel_type: "stat", config: { metric_key: "weather.home.rain", data_source: "custom" as const, stat_field: "latest" as const, unit: "mm" }, layout: { x: 9, y: 4, w: 3, h: 2 } },
      { title: "Snowfall", panel_type: "stat", config: { metric_key: "weather.home.snowfall", data_source: "custom" as const, stat_field: "latest" as const, unit: "cm" }, layout: { x: 9, y: 6, w: 3, h: 2 } },
    ],
  },
];
